### ISSUE TITLE
Custom Messages Type

### ISSUE THREAD

**Issue by Aquarius-M** [ayzerobug/mobile_chat_ui#5]
Is there a plan to support custom messages?

**Comment by Aquarius-M** [comment]
<img width="349" alt="image" src="https://github.com/ayzerobug/mobile_chat_ui/assets/47274897/4fad0eee-b0fa-408e-8266-ab45a2d52802">

and user avatar and name have UI problems

**Comment by ayzerobug** [comment]
Yes, support for custom message types will be provided in our coming releases. Issues on the User Avatar and name will be fix on in the next release
